version: '3.8'
services:
  smtp4dev:
    container_name: smtp4dev
    image: rnwood/smtp4dev:latest
    ports:
      - "2525:25"
      - "3100:80"
    volumes:
      - ./smtp4dev-data:/smtp4dev

volumes:
  smtp4dev-data:

